baseURL = "/"
title = "Shawn Medero"
MetaDataFormat = "yaml"
languageCode = "en-us"
DefaultContentLanguage = "en"
theme = "smedero"
disableHugoGeneratorInject = true
verbose = true
SectionPagesMenu = "main"
pluralizeListTitles = false
Paginate = 10

[params]
    favicon = ""
    micro_blog = "soypunk"
    twitter = "soypunk"
    github = "soypunk"
