baseurl = "http://shawn.medero.net"
languageCode = "en-us"
title = "shawn.medero.net"
canonifyurls = false
PluralizeListTitles = false

[author]
    name = "Shawn Medero"

[indexes]
    tag = "tags"
    topic = "topics"

[taxonomies]
	category = "topics"
	tag = "tags"

[params]
	blogSubtitle = "A panoply of dulcet thoughts."
	description = "Shawn Medero's personal website and blog."
	author = "Shawn Medero"