name: Create toots from feed items

on:
  workflow_run:
    workflows: ['Deploy Hugo site to Pages']
    types: [completed]
    branches:
        - 'main'
  workflow_dispatch:

jobs:
  Feed2Mastodon:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Checkout the repository to restore previous cache
      - name: Checkout
        uses: actions/checkout@v3

      # Look for new toots to create from items in the JSON feed
      - name: Feed to Mastodon
        uses: nhoizey/github-action-feed-to-mastodon@v2
        with:
          feedUrl: "https://shawn.medero.net/feed.json"
          mastodonInstance: "https://friend.camp"
          mastodonToken: ${{ secrets.MASTODON_TOKEN }}
          testMode: false

      # Make sure files are up to date if other commits have been pushed in the mean time
      - name: Pull any changes from Git
        run: git pull

      # Push changes in the cache files to the repository
      # See https://github.com/stefanzweifel/git-auto-commit-action#readme
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4