baseURL = 'https://shawn.medero.net/'
languageCode = 'en-US'
title = 'Shawn Medero'
disableKinds = ['taxonomy']
theme = 'sm'

enableRobotsTXT = true

[outputFormats.jsonfeed]
  mediaType = "application/json"
  baseName = "feed"
  isPlainText = true
  
[outputFormats.micro]
  mediatype = "application/json"
  baseName = "micro"
  isPlainText = true

[outputFormats.humanstxt]
	baseName = "humans"
	isPlainText = true
	mediaType = "text/plain"

[outputs]
  home = ["html", "jsonfeed", "rss", "humanstxt", "micro"]

[sitemap]
  changeFreq = ''
  disable = false
  filename = 'sitemap.xml'
  priority = -1

[taxonomies]
  tag = 'tags'
